#!/bin/sh
## Environment variable definition
##

for editor in nvim vim vi; do
  if type $editor >/dev/null 2>&1; then
    export EDITOR="$editor"
    break
  fi
done

for editor in git-editor; do
  if type $editor >/dev/null 2>&1; then
    export GIT_EDITOR="$editor"
    break
  fi
done

for pager in less lv more; do
  if type $pager >/dev/null 2>&1; then
    export PAGER="$pager"
    break
  fi
done

if type man-pager >/dev/null 2>&1; then
  export MANPAGER="man-pager" ## See ~/bin/man-pager
fi

if type ifne >/dev/null 2>&1; then
  ## Do NOT set GIT_PAGER that overrides `[pager]` settings in git-config(1)
  #export GIT_PAGER="ifne $PAGER"
  export HG_PAGER="ifne $PAGER" ## See ~/.hgrc
fi

## Remove "exec " if script should continue after this command. [SC2093]
export SHELLCHECK_OPTS='--exclude=SC2093'

if lsmod 2>/dev/null |grep '^vboxdrv ' >/dev/null; then
  ## Linux KVM cannot run with another hypervisor, such as VirtualBox
  export LIBGUESTFS_BACKEND_SETTINGS=force_tcg
fi

## Perl libs in $HOME by cpanm
if [ -d "$HOME/perl5/lib/perl5" ]; then
  case ":$PERL5LIB:" in
  *":$HOME/perl5/lib/perl5:"*)
    ;;
  *)
    export PERL5LIB="${PERL5LIB+$PERL5LIB:}$HOME/perl5/lib/perl5"
    ;;
  esac
fi

## Use Pod::Text::Color::Delight for perldoc(1) if available
if perl -MPod::Text::Color::Delight -e '' 2>/dev/null; then
  case " $PERLDOC " in
  *" -MPod::Text::Color::Delight "*)
    ;;
  *)
    export PERLDOC="${PERLDOC+$PERLDOC }-MPod::Text::Color::Delight"
    ;;
  esac
fi
