#!/bin/sh
## Aliases and functions definition for bash, zsh
## Author: SATOH Fumiyasu
## Date: 2009-03-04, since 1999

## Generic
## ======================================================================

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias cdpwd='cd `pwd`'

alias ko='/bin/echo ""; /bin/echo "c"; stty sane; reset'
alias lang-c='env LC_ALL=C LANG=C'
alias nkf-x='nkf -x -m0'

alias ps-x="ps -efly"
alias ps-u="ps -fu $LOGNAME"
alias pstree-x='pstree -acpu'
alias dstat-full='dstat -Tclmdrn'
alias dstat-mem='dstat -Tclm'
alias dstat-cpu='dstat -Tclr'
alias dstat-net='dstat -Tclnd'
alias dstat-disk='dstat -Tcldr'

alias wcp='wget -m -l3 --no-parent'
alias whois-jp='whois -h whois.jprs.jp'
alias whois-jp-en='whois_jp_en'
whois_jp_en() {
  whois -h whois.jprs.jp ${1+"$1/e"}
}

cal() {
  if [ $# -eq 0 ]; then
    command cal -3
  else
    command cal ${1+"$@"}
  fi
}

ssh()
{
  if [ -t 0 ] && [ -t 1 ]; then
    case "$TERM" in
    *term*|*vt*)
      for __arg in ${1+"$@"}; do
        case "$__arg" in
        -*)
          ;;
        *)
          print -Pn "\e]2;ssh $__arg (`hostname`:${TTY#/dev/})\a"
          break
          ;;
        esac
      done
    esac
  fi

  command ssh ${1+"$@"}
}

alias telnet-u='nc.openbsd -U'
## UNIX crypt(1) emulation by mcrypt(1)
alias crypt='mcrypt -a enigma --keymode scrypt --bare'

alias cgrep='grep --color=always'
alias cegrep='egrep --color=always'

alias ra='. $HOME/.profile'

alias xclip-c='xclip -selection clipboard'
alias acroread='command acroread -openInNewWindow'

alias isoinfo-x='isoinfo -lR -i'
type genisoimage >/dev/null 2>&1 && mkisofs="genisoimage" || mkisofs="mkisofs"
alias mkisofs-x="env TZ=UTC $mkisofs -uid 0 -gid 0 -J -input-charset UTF-8 -r -iso-level 1"
#alias mkisofs-x="env TZ=UTC $mkisofs -uid 0 -gid 0 -J -R -iso-level 4"
#alias mkisofs-y="env TZ=UTC $mkisofs -uid 0 -gid 0 -J -R -r -iso-level 4"
unset mkisofs
type wodim >/dev/null 2>&1 && cdrecord="wodim" || cdrecord="cdrecord"
alias cdrecord-x="$cdrecord -v"
alias cdrw-blank="$cdrecord -v blank=fast"
alias cdrw-blank-slow="$cdrecord -v blank=all"
unset cdrecord

alias strace-x='strace -ffttTCx -s 9999'
alias truss-sol-x='truss -aedlDE -v all'
alias truss-sol-xa='truss -aedlDE -v all -r all -w all'
alias truss-sol-xt='truss -aedlDE -v all'
alias truss-sol-xat='truss -aedlDE -v all -r all -w all'
alias truss-aix-x='truss -aedlD'
alias gcc-macros='gcc -E -dM - </dev/null'
alias gcc-x='gcc -O2 -march=native -pipe -fomit-frame-pointer -flto'

for cmd in diff make grep egrep fgrep; do
  type "g$cmd" >/dev/null 2>&1 && alias "$cmd=g$cmd"
done

if type "g$cmd" >/dev/null 2>&1; then
  alias diff='LC_ALL=C gdiff'
else
  alias diff='LC_ALL=C diff'
fi
if ! type colordiff >/dev/null 2>&1; then
  colordiff()
  {
    { [ -z "${1-}" ] && cat || LC_ALL=C diff "$@"; } \
    |sed -e '/^--- /n;s/^[+>]/\x1b\[32m+/;s/^[-<]/\x1b[31m-/;s/$/\x1b[0m/'
  }
fi

if type vim >/dev/null 2>&1; then
  alias vi="${vim_env}vim"
  alias vidos="${vim_env}"'vim -u "$HOME/.vimrc.dos"'
  alias vimac="${vim_env}"'vim -u "$HOME/.vimrc.mac"'
  unset vim_env
fi

alias git-log='git log --graph --decorate --oneline'

alias git-patch='git_patch'
git_patch() {
  if [ $# -eq 1 ]; then
    git format-patch --stdout "$1^..$1"
  else
    git format-patch --stdout "$1..$2"
  fi
}

alias git-patch-mail='git_patch_mail'
git_patch_mail() {
  if [ $# -eq 1 ]; then
    git format-patch --attach --stdout "$1^..$1"
  else
    git format-patch --attach --stdout "$1..$2"
  fi
}

#type lv >/dev/null 2>&1 || { type less >/dev/null 2>&1 && alias lv='less'; }

if [ -f "$HOME/lib/vim/plugin/less.vim" ]; then
  lvv() {
    if [ $# -eq 0 ]; then
      vim --cmd 'let no_plugin_maps = 1' -c 'source $HOME/lib/vim/plugin/less.vim' -
    else
      vim --cmd 'let no_plugin_maps = 1' -c 'source $HOME/lib/vim/plugin/less.vim' "$@"
    fi
  }
elif ls /usr/share/vim/vim*/macros/less.sh >/dev/null 2>&1; then
  alias lvv="`ls /usr/share/vim/vim*/macros/less.sh |sed -n '$p'`"
fi

termconv()
{
  if [ -t 0 ] && [ -t 1 ]; then
    :
  else
    shift
    "$@"
    return $?
  fi

  proc_code="$1"; shift
  proc_code_n="`echo "$proc_code" |sed 's/[-_]//g' |tr A-Z a-z`"

  if [ x"${LANG:-C}" = x"C" ]; then
    term_code="utf-8"
  else
    term_code="`echo "$LANG" |sed 's/^.*\.//'`"
  fi
  term_code_n="`echo "$term_code" |sed 's/[-_]//g' |tr A-Z a-z`"

  if [ x"$proc_code_n" != x"$term_code_n" ]; then
    cocot -t "$term_code" -p "$proc_code" -- "$@"
  else
    "$@"
  fi
}

## Convert office documents into CSV format in UTF-8 encoding
alias unoconv-csv='unoconv -i ,,76 -f csv'

## NOTE: Some man(1) command does not see LC_ALL. :-(
alias mane='LC_ALL=C LANG=C man'

alias mans10='MANPATH=/srv/os/solaris-10/usr/share/man man'
alias mans10e='LC_ALL=C LANG=C MANPATH=/srv/os/solaris-10/usr/share/man man'
alias mans11='MANPATH=/srv/os/solaris-11/usr/share/man man'
alias mans11e='LC_ALL=C LANG=C MANPATH=/srv/os/solaris-11/usr/share/man man'
alias manc5='MANPATH=/srv/os/centos-5/usr/share/man man'
alias manc5e='LC_ALL=C LANG=C MANPATH=/srv/os/centos-5/usr/share/man man'
alias mana5='MANPATH=/srv/os/aix-5/usr/share/man man'
alias mana5e='LC_ALL=C LANG=C MANPATH=/srv/os/aix-5/usr/share/man man'
alias manf9='MANPATH=/srv/os/freebsd-9/usr/share/man man'
alias manf9e='LC_ALL=C LANG=C MANPATH=/srv/os/freebsd-9/usr/share/man man'
alias manf8='MANPATH=/srv/os/freebsd-8/usr/share/man man'
alias manf8e='LC_ALL=C LANG=C MANPATH=/srv/os/freebsd-8/usr/share/man man'

mancat()
{
  nroff -man "$@" |"$PAGER"
}

#shar -macDB --no-i18n -n ... -o ...

alias rpm-qq='rpm_qq'
rpm-qq()
{
  rpm -q --qf "`rpm --querytags |sort |sed 's/^\(.*\)$/\1: %{\1}/'`\n" "$@" \
  |egrep -v '^HEADER|: $|: \(none\)$'
}

alias rpm-dump='rpm_dump'
rpm_dump()
{
  [ -n "$1" ] || { echo "Usage: rpm-dump NAME.rpm"; return 1; }
  rpm2cpio "$1" | (
    [ -n "$2" ] || cd "$2" || exit 1
    cpio -id
  )
}

## X11
## ======================================================================

if type xbacklight >/dev/null 2>&1; then
  for n in 1 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100; do
    alias $n="xbacklight -set $n"
  done
fi

## C-shell compatibility
## ======================================================================

alias source='.'

which_csh()
{
  for cmd in ${1+"$@"}; do
    type=`type "$cmd"`
    head=`echo "$type" | head -1`
    desc=`echo $head | sed 's/^[^ ]* [^ ][^ ]* \([^ ]*\).*$/\1/'`
    case $desc in
    /* | hashed )	## command
      echo $head | sed -e "s#^[^/]*/#/#" -e "s#[)']"'$##'
      ;;
    a | aliased | * )	## a function, alias or others
      echo $head
      ;;
    esac
  done
}

if type which >/dev/null 2>&1; then
  : OK
else
  alias which='which_csh'
fi

## EOF
