#!/bin/sh
##
## Build ssh-agent(1) environment
## Copyright (c) 1999-2012 SATOH Fumiyasu. All rights reserved.
##
## Date: 2012-05-04, since 1999-09-20

[ -n "$PS1" ] || return

## FIXME!
## http://blog.gcd.org/archives/50713097.html

if [ -S "${SSH_AUTH_SOCK-/dev/null}" ]; then
  : OK, 'ForwardAgent yes' on client is enabled
else
  SSH_AUTH_SOCK="$HOME/.ssh/agent.sock.$HOSTNAME"
  SSH_AGENT_ENV="$HOME/.ssh/agent.env.$HOSTNAME"
  export SSH_AUTH_SOCK SSH_AGENT_ENV

  . "$SSH_AGENT_ENV" >/dev/null 2>&1
  if [ -n "$SSH_AUTH_SOCK_REAL" ] && [ -S "$SSH_AUTH_SOCK_REAL" ]; then
    : OK, ssh-agent on this host is already running
  elif type ssh-agent >/dev/null 2>&1; then
    ssh-agent |sed 's/SSH_AUTH_SOCK/SSH_AUTH_SOCK_REAL/g' >"$SSH_AGENT_ENV"
    . "$SSH_AGENT_ENV" >/dev/null
    rm -f "$SSH_AUTH_SOCK"
    ln -s "$SSH_AUTH_SOCK_REAL" "$SSH_AUTH_SOCK"
  fi
fi

